name: Create GitHub Repository 

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      project-team-name:
        required: true
        type: string

jobs:
  create-gh-repo:
    runs-on: ubuntu-latest
    name: Create GitHub Repository 
    steps:
      - run: gh repo create $PROJECT-NAME --team $PROJECT-TEAM-NAME --private --disable-wiki 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT-NAME: ${{ inputs.project-name }}
          PROJECT-TEAM-NAME: ${{ inputs.project-team-name }}
          