name: Create GitHub Repository 

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      project-team-name:
        required: true
        type: string

jobs:
  create-gh-repo:
    runs-on: ubuntu-latest
    name: Create GitHub Repository 
    steps:
      - run: gh repo create $PROJECTNAME --team $PROJECTTEAMNAME --private --disable-wiki 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECTNAME: ${{ inputs.project-name }}
          PROJECTTEAMNAME: ${{ inputs.project-team-name }}
          