name: Create GitHub Repository 

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      project-team-name:
        required: true
        type: string

jobs:
  create-gh-repo:
    runs-on: ubuntu-latest
    name: Create GitHub Repository 
    steps:
      - run: |
            mkdir '${{ inputs.project-name }}'
            cd '${{ inputs.project-name }}'
            git config --global init.defaultBranch main
            git config --global user.email "repobot@contoso.com"
            git config --global user.name "Repo Bot"
            git init
            echo "# New Project Repository" >> README.md
            git add .
            git commit -m "Provision Repository"
        shell: bash

      - run: gh repo create --private
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          